module.exports = {
  USER_ROLES: {
    USER: 'USER',
    ADMIN: 'ADMIN',
    CASHIER: 'CASHIER',
    OPERATION: 'OPERATION',
  },
  BOOKING_STATUS: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED',
  },
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
  },
  PAYMENT_COLLECTOR: {
    CASHIER: 'CASHIER',
    BANK: 'BANK',
    ONLINE: 'ONLINE',
    MOBILE_BANKING: 'MOBILE_BANKING',
    CARD: 'CARD',
  },
  SEAT_LAYOUTS: {
    TWO_BY_TWO: '2x2',
    THREE_BY_TWO: '3x2',
  },
  DEFAULT_SEAT_LOCK_DURATION: 10, // minutes
};

